export default {
    unDuplicateIdPass: false,
    memberInfoAfterSignIn: {},
    signInCheckValue: false,
    userToken: "",
    shoppingBucketProductItemList: [],
    mainPageProductListByHandmade: [],
    mainPageProductListByKnowHow: [],
    mainPageProductListByHobby: [],
    mainPageProductImgListByHandmade: [],
    mainPageProductImgListByKnowHOw: [],
    mainPageProductImgListByHobby: [],
    product: {},
    productList: [],
    myOrderInfoList: [],
    searchResultList: [],
    mainPageNextProductList: [],
    mainPageNextProductImgList: [],
    myQnaList: [],
    sellerOrderList: [],
    handmadeProductRatingValue: [],
    knowhowProductRatingValue: [],
    hobbyProductRatingValue: [],
    productQnaList: [],
    myPageCategoryItems: [
        {title: "최근 주문내역"},
        {title: "문의 내역"},
        {title: "작성한 리뷰 내역"},
        {title: "최근 본 상품 내역"},
    ],
    productReviewList: [],
    reviewImage: [],
    productReviewCnt: "",
    qnaBeforeAnswerList: [],
    qnaCompleteList: [],
    myReviewList: [],
    recentlyViewedProductListTmp: [],
    recentlyViewedProductList: [],
    productRatingValue: [],
    productReadRatingValue: [],
    sellerOrderListCount: 0,
    reviewWriteCheckValue: [],
    sellerInfoData: {}
}