export default {
    unDuplicateIdPass: false,
    memberInfoAfterSignIn: {},
    signInCheckValue: false,
    userToken: "",
    shoppingBucketProductItemList: [],
    mainPageProductListByHandmade: [],
    mainPageProductListByKnowHow: [],
    mainPageProductListByHobby: [],
    mainPageProductImgListByHandmade: [],
    mainPageProductImgListByKnowHOw: [],
    mainPageProductImgListByHobby: [],
    product: {},
    productList: [],
    myOrderInfoList: [],
    searchResultList: [],
    mainPageNextProductList: [],
    mainPageNextProductImgList: [],
    myQnaList: [],
    sellerOrderList: [],
    handmadeProductRatingValue: [],
    knowhowProductRatingValue: [],
    hobbyProductRatingValue: [],
    productQnaList: [],
    myPageCategoryItems: [
        {title: "최근 주문", path: '/buyer-orderInfo'},
        {title: "나의 문의", path: '/buyer-qna'},
        {title: "나의 후기", path: '/buyer-review'},
        {title: "최근 본 상품", path: '/buyer-recently-view'},
        {title: "찜한 아이디어", path: '/buyer-favorite'}
    ],
    productReviewList: [],
    reviewImage: [],
    productReviewCnt: "",
    qnaBeforeAnswerList: [],
    qnaCompleteList: [],
    myReviewList: [],
    recentlyViewedProductListTmp: [],
    recentlyViewedProductList: [],
    productRatingValue: [],
    productReadRatingValue: [],
    sellerOrderListCount: [],
    reviewWriteCheckValue: [],
    sellerInfoData: {},
    sellerTotalInfo: {},
    handmadeReviewCnt: [],
    knowhowReviewCnt: [],
    hobbyReviewCnt: [],
    handmadeFavoriteProductCheck: [],
    knowhowFavoriteProductCheck: [],
    hobbyFavoriteProductCheck: [],
    favoriteProductList: [],
    favoriteProductInfoList: [],
    favoriteProductRatingValue: [],
    productListByFilter: [],
    hobbyProductListByFilter: [],
    knowhowProductByFilter: [],
    filterType: "",
    hobbyProductListByFilterLastLength: 0,
    knowhowProductListByFilterLastLength: 0,
    handmadeProductListByFilterLastLength: 0


}