export default {
    unDuplicateIdPass: false,
    memberInfoAfterSignIn: {},
    signInCheckValue: false,
    userToken: "",
    shoppingBucketProductItemList: [],
    mainPageProductListByHandmade: [],
    mainPageProductListByKnowHow: [],
    mainPageProductListByHobby: [],
    mainPageProductImgListByHandmade: [],
    mainPageProductImgListByKnowHOw: [],
    mainPageProductImgListByHobby: [],
    product: {},
    productList: [],
    myOrderInfoList: [],
    searchResultList: [],
    mainPageNextProductList: [],
    mainPageNextProductImgList: [],
    myQnaList: [],
    sellerOrderList: [],
    handmadeProductRatingValue: [],
    knowhowProductRatingValue: [],
    hobbyProductRatingValue: [],
}