
server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://buydia-db/buy_idea_db?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    username: eddi
    password: [db비밀번호]
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect

  cache:
    type: redis

  redis:
    host: buy_dia-redis
    port: 6379

  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
