version: "3.7"
services:
  db:
    image: "mysql:8.0"
    container_name: buydia-db
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/mysql/logs:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - app
  redis:
    image: redis:7.0.4
    command: redis-server --port 6379
    container_name: buydia-redis
    hostname: redis_standalone
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
    depends_on:
      - db
    networks:
      - app
  server:
    image: "buydia/buydia-server:latest"
    build: .
    container_name: buydia-server
    restart: unless-stopped
    volumes:
      - appdata:/app
    depends_on:
      - redis
    ports:
      - "8888:7777"
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh db:3306 -t 15
        java -jar /app.jar
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  dbdata:
    driver: local
  appdata:
    driver: local